### ISSUE TITLE
Problem with object counting

### ISSUE THREAD

**Issue by compVisual** [roboflow/roboflow-computer-vision-utilities#13]
Hi, I'm trying to make an object counter with a yolo v8 model that I trained localy but when I try to adapt your code I get this error: IndexError: too many indices for tensor of dimension 2, on this line of code: if prediction['class'] in target_classes: inside the count_objects function.

Here is my code: 

```
def count_objects(predictions, target_classes):
    """
    Helper method to count the number of objects in an image for a given class
    :param predictions: predictions returned from calling the predict method
    :param target_class: str, target class for object count
    :return: dictionary with target class and total count of occurrences in image
    """
    object_counts = {x:0 for x in target_classes}
    for prediction in predictions:
        if prediction['class'] in target_classes:
            object_counts[prediction['class']] += 1
        elif prediction['class'] not in target_classes:
            object_counts[prediction['class']] = 1

    present_objects = object_counts.copy()

    for i in object_counts:
        if object_counts[i] < 1:
            present_objects.pop(i)

    return present_objects

predictions = model.predict(source = "folderImages", conf = 0.6)
class_counts= count_objects(predictions, model.names)

print('/n', "Class Counts:", '/n')
print(class_counts)
```

**Comment by mo-traor3-ai** [comment]
This repository will work for your YOLOv8 predictions if you [upload the model weights]() to Roboflow for Roboflow Deploy.

YOLOv8 model weights not hosted with Roboflow for Roboflow Deploy for Hosted Inference API, web browser, edge device, or local deployment, will not process inference with the current code in this repository.

You will want to use Supervision in this case: https://github.com/roboflow/supervision
* `supervision/detection/core`: https://roboflow.github.io/supervision/detection/core/
* `supervision/detection/utils`: https://roboflow.github.io/supervision/detection/utils/
* `supervision/detection/annotate`: https://roboflow.github.io/supervision/detection/annotate/

There are 2 great tutorials here for using Supervision:
1. [Detect and Count Objects in Polygon Zone with YOLOv5 / YOLOv8 / Detectron2 + Supervision](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-detect-and-count-objects-in-polygon-zone.ipynb)
2. [Track and Count Vehicles with YOLOv8 + ByteTRACK + Supervision](https://github.com/roboflow-ai/notebooks/blob/main/notebooks/how-to-track-and-count-vehicles-with-yolov8.ipynb)

Supervision-versions of the code in this repo will be adding over the next few weeks.
